version: '3'
services: 
  web:
    build: .
    depends_on: 
      - db
    ports: 
      - "8080:8080"
    environment:
      DB_HOST: mysql_database
  db: 
    image: mysql:8.0.15
    container_name: mysql_database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: db_password
    expose:
      - "3306"
    ports:
      - "3306:3306"

    volumes:
      - db-data:/foo

volumes:
  db-data: